import { ChatConversationInfo, ChatMessageInfo } from '@/core/sdk/communication';

// Mock users
const mockUsers = {
  currentUser: {
    id: 'user-1',
    email: 'me@example.com',
    phoneNumber: '+1234567890',
    role: 'USER',
    avatar: 'https://ui-avatars.com/api/?name=Me&background=228be6&color=fff',
    name: 'Me',
    isProductUploadSubscriptionActive: true,
    followerCount: 150,
  },
  john: {
    id: 'user-2',
    email: 'john@example.com',
    phoneNumber: '+1234567891',
    role: 'VENDOR',
    avatar: 'https://ui-avatars.com/api/?name=John+Doe&background=40c057&color=fff',
    name: 'John Doe',
    isProductUploadSubscriptionActive: true,
    followerCount: 320,
  },
  sarah: {
    id: 'user-3',
    email: 'sarah@example.com',
    phoneNumber: '+1234567892',
    role: 'VENDOR',
    avatar: 'https://ui-avatars.com/api/?name=Sarah+Smith&background=be4bdb&color=fff',
    name: 'Sarah Smith',
    isProductUploadSubscriptionActive: false,
    followerCount: 85,
  },
  mike: {
    id: 'user-4',
    email: 'mike@example.com',
    phoneNumber: '+1234567893',
    role: 'VENDOR',
    avatar: 'https://ui-avatars.com/api/?name=Mike+Johnson&background=fab005&color=fff',
    name: 'Mike Johnson',
    isProductUploadSubscriptionActive: true,
    followerCount: 200,
  },
  emma: {
    id: 'user-5',
    email: 'emma@example.com',
    phoneNumber: '+1234567894',
    role: 'VENDOR',
    avatar: 'https://ui-avatars.com/api/?name=Emma+Wilson&background=f06595&color=fff',
    name: 'Emma Wilson',
    isProductUploadSubscriptionActive: true,
    followerCount: 450,
  },
};

// Helper to create timestamps
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
const minsAgo = (mins: number) => new Date(Date.now() - mins * 60 * 1000).toISOString();

// Mock conversations
export const mockConversations: ChatConversationInfo[] = [
  {
    id: 'conv-1',
    unreadMessagesCount: 2,
    lastConversationMessage: 'Thanks boss! Good morning',
    lastConversationTimestamp: minsAgo(15),
    user1: mockUsers.currentUser,
    user2: mockUsers.john,
  },
  {
    id: 'conv-2',
    unreadMessagesCount: 0,
    lastConversationMessage: 'The goats are ready for pickup',
    lastConversationTimestamp: hoursAgo(2),
    user1: mockUsers.currentUser,
    user2: mockUsers.sarah,
  },
  {
    id: 'conv-3',
    unreadMessagesCount: 5,
    lastConversationMessage: 'What is the best price you can do?',
    lastConversationTimestamp: hoursAgo(5),
    user1: mockUsers.mike,
    user2: mockUsers.currentUser,
  },
  {
    id: 'conv-4',
    unreadMessagesCount: 0,
    lastConversationMessage: 'I will send the payment soon',
    lastConversationTimestamp: hoursAgo(24),
    user1: mockUsers.currentUser,
    user2: mockUsers.emma,
  },
];

// Mock messages for each conversation
export const mockMessages: Record<string, ChatMessageInfo[]> = {
  'conv-1': [
    {
      id: 'msg-1-1',
      content: 'Hello! I saw your listing for the cattle',
      isRead: [],
      timestamp: hoursAgo(3),
      sender: mockUsers.john.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-1',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-1-2',
      content: 'Hi! Yes, they are still available. Which one are you interested in?',
      isRead: [parseInt(mockUsers.john.id.split('-')[1])],
      timestamp: hoursAgo(2.5),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.john.id,
      conversation: 'conv-1',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-1-3',
      content: 'The Holstein breed. How old is it?',
      isRead: [],
      timestamp: hoursAgo(2),
      sender: mockUsers.john.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-1',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-1-4',
      content: 'It is 2 years old, very healthy and well-fed',
      isRead: [parseInt(mockUsers.john.id.split('-')[1])],
      timestamp: hoursAgo(1.5),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.john.id,
      conversation: 'conv-1',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-1-5',
      content: 'Thanks boss! Good morning',
      isRead: [],
      timestamp: minsAgo(15),
      sender: mockUsers.john.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-1',
      hasCTA: false,
      ctaType: '',
    },
  ],
  'conv-2': [
    {
      id: 'msg-2-1',
      content: 'Hi Sarah, do you have any goats available?',
      isRead: [parseInt(mockUsers.sarah.id.split('-')[1])],
      timestamp: hoursAgo(48),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.sarah.id,
      conversation: 'conv-2',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-2-2',
      content: 'Yes I do! I have 5 healthy goats. Would you like to see them?',
      isRead: [],
      timestamp: hoursAgo(47),
      sender: mockUsers.sarah.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-2',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-2-3',
      content: 'That would be great! When can I come?',
      isRead: [parseInt(mockUsers.sarah.id.split('-')[1])],
      timestamp: hoursAgo(46),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.sarah.id,
      conversation: 'conv-2',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-2-4',
      content: 'You can come tomorrow morning around 10am',
      isRead: [],
      timestamp: hoursAgo(24),
      sender: mockUsers.sarah.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-2',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-2-5',
      content: 'Perfect, I will be there!',
      isRead: [parseInt(mockUsers.sarah.id.split('-')[1])],
      timestamp: hoursAgo(23),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.sarah.id,
      conversation: 'conv-2',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-2-6',
      content: 'The goats are ready for pickup',
      isRead: [],
      timestamp: hoursAgo(2),
      sender: mockUsers.sarah.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-2',
      hasCTA: false,
      ctaType: '',
    },
  ],
  'conv-3': [
    {
      id: 'msg-3-1',
      content: 'Good day! I am interested in your sheep',
      isRead: [],
      timestamp: hoursAgo(10),
      sender: mockUsers.mike.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-3',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-3-2',
      content: 'Hello! Which ones caught your eye?',
      isRead: [parseInt(mockUsers.mike.id.split('-')[1])],
      timestamp: hoursAgo(9),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.mike.id,
      conversation: 'conv-3',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-3-3',
      content: 'The Merino sheep. The price is ₦150,000 right?',
      isRead: [],
      timestamp: hoursAgo(8),
      sender: mockUsers.mike.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-3',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-3-4',
      content: 'Yes, that is the listed price',
      isRead: [parseInt(mockUsers.mike.id.split('-')[1])],
      timestamp: hoursAgo(7),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.mike.id,
      conversation: 'conv-3',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-3-5',
      content: 'What is the best price you can do?',
      isRead: [],
      timestamp: hoursAgo(5),
      sender: mockUsers.mike.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-3',
      hasCTA: false,
      ctaType: '',
    },
  ],
  'conv-4': [
    {
      id: 'msg-4-1',
      content: 'Hi! Your poultry farm looks amazing!',
      isRead: [parseInt(mockUsers.emma.id.split('-')[1])],
      timestamp: hoursAgo(72),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.emma.id,
      conversation: 'conv-4',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-4-2',
      content: 'Thank you so much! We take pride in our chickens',
      isRead: [],
      timestamp: hoursAgo(71),
      sender: mockUsers.emma.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-4',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-4-3',
      content: 'Do you sell in bulk? I need about 50 chickens',
      isRead: [parseInt(mockUsers.emma.id.split('-')[1])],
      timestamp: hoursAgo(70),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.emma.id,
      conversation: 'conv-4',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-4-4',
      content: 'Yes we do! For 50 chickens, we can give you a 10% discount',
      isRead: [],
      timestamp: hoursAgo(48),
      sender: mockUsers.emma.id,
      recipient: mockUsers.currentUser.id,
      conversation: 'conv-4',
      hasCTA: false,
      ctaType: '',
    },
    {
      id: 'msg-4-5',
      content: 'That sounds great! I will send the payment soon',
      isRead: [parseInt(mockUsers.emma.id.split('-')[1])],
      timestamp: hoursAgo(24),
      sender: mockUsers.currentUser.id,
      recipient: mockUsers.emma.id,
      conversation: 'conv-4',
      hasCTA: false,
      ctaType: '',
    },
  ],
};

export const MOCK_CURRENT_USER_ID = mockUsers.currentUser.id;



